version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/setup-dependencies"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"
