# Default GitHub labels
- color: d73a4a
  name: bug
  description: Something isn't working
- color: 0075ca
  name: documentation
  description: Improvements or additions to documentation
- color: 0366d6
  name: dependencies
  description: Pull requests that update a dependency file
- color: cfd3d7
  name: duplicate
  description: This issue or pull request already exists
- color: a2eeef
  name: enhancement
  description: Functionality that enhances existing features
- color: 7057ff
  name: good first issue
  description: Good for newcomers
- color: 008672
  name: help wanted
  description: We are looking for community help
- color: e4e669
  name: invalid
  description: This doesn't seem right
- color: d876e3
  name: question
  description: Further information is requested
- color: d876e3
  name: wontfix
  description: The issue is expected and will not be fixed
# Custom
- color: 00f2de
  name: challenge
  description: Adding/updating a challenge
