# labels auto assigned to PR, keep in sync with labels.yml
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["README.md"]
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/poetry.lock"]
      - head-branch: ["^dependabot"]
challenge:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["challenges/**/*"]
